# 2023-12-16 21:30
name: test-latest

on:
  workflow_dispatch:
    inputs:
      tag1:
        description: tag1
        default: 'tag1latest'
        required: true
      tag2:
        description: tag2
        default: 'tag2latest'
        required: true
      tag3:
        description: tag3
        default: 'tag3latest'
        required: true

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create archive 1
        continue-on-error: true
        uses: deep-soft/zip-release@v2
        with:
          type: 'zip'
          filename: "${{ inputs.tag1 }}"
          directory: '.'
          exclusions: '*node_modules*'
          recursive_exclusions: ''
          path: './dist'
          env_variable: ZIP_RELEASE_ARCHIVE
        # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Prepare artifact 1 list
        continue-on-error: true
        shell: bash
        run: |
          echo "${{ env.ZIP_RELEASE_ARCHIVE }}" >> the_file_list

      - name: Publish artifact 1
        continue-on-error: true
        uses: deep-soft/action-gh-release@latest
        with:
          draft: true
          tag_name: ${{ inputs.tag1 }}
          files: |
            the_file_list
            ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Create archive 2
        continue-on-error: true
        uses: deep-soft/zip-release@v2
        with:
          type: 'zip'
          filename: "${{ inputs.tag2 }}"
          directory: '.'
          exclusions: '*node_modules*'
          recursive_exclusions: ''
          path: './src'
          env_variable: ZIP_RELEASE_ARCHIVE
        # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Prepare artifact 2 list
        continue-on-error: true
        shell: bash
        run: |
          echo "${{ env.ZIP_RELEASE_ARCHIVE }}" >> the_file_list

      - name: Publish artifact 2
        continue-on-error: true
        uses: deep-soft/action-gh-release@latest
        with:
          draft: true
          tag_name: ${{ inputs.tag2 }}
          filelist: the_file_list

      - name: Publish artifact 3
        continue-on-error: true
        uses: deep-soft/action-gh-release@latest
        with:
          draft: true
          tag_name: ${{ inputs.tag3 }}
          filelist: the_file_list
          files: |
            the_file_list
